# Generated by Django 3.1.7 on 2021-04-02 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='News',
            new_name='New',
        ),
        migrations.RenameModel(
            old_name='Rewiews',
            new_name='Rewiew',
        ),
        migrations.RenameField(
            model_name='rewiew',
            old_name='vide',
            new_name='video',
        ),
        migrations.RenameField(
            model_name='sliderimage',
            old_name='color',
            new_name='color_text',
        ),
    ]
