# Generated by Django 3.1.7 on 2021-04-09 16:37

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminboard', '0003_auto_20210409_1831'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='new',
            name='content',
        ),
        migrations.RemoveField(
            model_name='new',
            name='description',
        ),
        migrations.RemoveField(
            model_name='new',
            name='name',
        ),
        migrations.AddField(
            model_name='new',
            name='url',
            field=models.URLField(default=' ', max_length=250),
        ),
        migrations.AlterField(
            model_name='new',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='title'),
        ),
        migrations.AlterField(
            model_name='new',
            name='title',
            field=models.CharField(db_index=True, max_length=70),
        ),
    ]
