# Generated by Django 3.1.7 on 2021-04-09 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminboard', '0004_auto_20210409_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='url',
            field=models.URLField(default='', max_length=250),
        ),
    ]
