# Generated by Django 3.1.7 on 2021-04-09 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminboard', '0005_auto_20210409_2238'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='shortDescription',
            field=models.TextField(default='', max_length=300),
        ),
    ]
