# Generated by Django 3.1.7 on 2021-04-09 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminboard', '0006_new_shortdescription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='new',
            name='slug',
        ),
        migrations.AlterField(
            model_name='new',
            name='shortDescription',
            field=models.TextField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='review',
            name='video',
            field=models.URLField(default='', max_length=250),
        ),
    ]
