# Generated by Django 3.1.7 on 2021-03-13 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20210313_1728'),
    ]

    operations = [
        migrations.RenameField(
            model_name='popularproduct',
            old_name='newprice',
            new_name='oldprice',
        ),
    ]
