# Generated by Django 3.1.7 on 2021-03-20 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_usersdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='news',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=30)),
                ('image', models.ImageField(blank=True, upload_to='images')),
                ('information', models.CharField(max_length=1000)),
            ],
        ),
        migrations.DeleteModel(
            name='usersData',
        ),
    ]
